### ISSUE TITLE
批量导入本地漫画报错

### ISSUE THREAD

**Issue by nief12** [venera-app/venera#115]
### Description

选择了文件夹，但会报两种错误

### Version

v1.1.2

### Operating system

Android

### logs

ZipException: Failed to open file.
#0      new ZipFile.open (package:zip_flutter/src/zip_dart_base.dart:87)
#1      new ZipFile.openRead (package:zip_flutter/src/zip_dart_base.dart:95)
#2      isolatesExtract (package:zip_flutter/src/multithreading.dart:7)
#3      ZipFile.openAndExtractAsync (package:zip_flutter/src/zip_dart_base.dart:316)
#4      CBZ.import (package:venera/utils/cbz.dart:65)
#5      ImportComic.multipleCbz (package:venera/utils/import_comic.dart:51)
<asynchronous suspension>
#6      _ImportComicsWidgetState.selectAndImport (package:venera/pages/home_page.dart:633)
<asynchronous suspension>

Comic source not found.
#0      HistoryImageProvider.load (package:venera/foundation/image_provider/history_image_provider.dart:28)
#1      BaseImageProvider._loadBufferAsync (package:venera/foundation/image_provider/base_image_provider.dart:80)
<asynchronous suspension>
#2      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:1013)
<asynchronous suspension>

### Screenshot or video

https://github.com/user-attachments/assets/4206b52e-60a2-41f2-b3e4-fd2ff7c2a36c

**Comment by nief12** [comment]
多个漫画文件也试过，也是报这两种错误
