### ISSUE TITLE
本地或下载的漫画有概率打开报错

### ISSUE THREAD

**Issue by nief12** [venera-app/venera#121]
### Description

复现需要清除app后台，然后打开已经观看过的本地漫画，会报如图错误，重试后正常加载。
![Screenshot_20241227_011507_com_github_wgh136_venera_MainActivity](https://github.com/user-attachments/assets/2552834c-3d33-4137-a140-9d1a1b2da5c9)

### Version

v1.1.3

### Operating system

Android

### logs

Exception: Empty image data
#0      BaseImageProvider._loadBufferAsync (package:venera/foundation/image_provider/base_image_provider.dart:106)
<asynchronous suspension>
#1      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:1013)
<asynchronous suspension>

**Comment by nief12** [comment]
我研究了一下，这个复现需要设置新的存储路径，在默认路径是不会报错的。

**Comment by pkuislm** [comment]
没啥头绪，我需要本地复现一下

**Comment by nief12** [comment]
> @pkuislm 有什么想法吗

这个bug我影响中是在第91个议题后，对本地漫画进行了预加载后出现的

**Comment by xihale** [comment]
自定义存储路径后，相应路径下只有 cover.jpg 缓存文件。

是不是缓存写入和缓存加载使用了不统一的路径索引？
