### ISSUE TITLE
[Bug]: Type cast error: '_Map<String, dynamic>' cannot be cast to 'double?' in ScrollPosition.restoreScrollOffset

### ISSUE THREAD

**Issue by boa-z** [venera-app/venera#94]
### Description

reproduce: click favorite, click any other tab, then click favorite 

### Version

1.1.0

### Operating system

iOS, macOS

### logs

```log
type '_Map<String, dynamic>' is not a subtype of type 'double?' in type cast
#0      ScrollPosition.restoreScrollOffset (package:flutter/src/widgets/scroll_position.dart:534)
#1      new ScrollPosition (package:flutter/src/widgets/scroll_position.dart:203)
#2      new ScrollPositionWithSingleContext (package:flutter/src/widgets/scroll_position_with_single_context.dart)
#3      ScrollController.createScrollPosition (package:flutter/src/widgets/scroll_controller.dart:301)
#4      ScrollableState._updatePosition (package:flutter/src/widgets/scrollable.dart:626)
#5      ScrollableState.didChangeDependencies (package:flutter/src/widgets/scrollable.dart:661)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5780)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
#12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
#13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
#18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
#19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#21     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7049)
#22     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7061)
#23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6914)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6914)
#29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6914)
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)...
```

### Screenshot or video

<img width="468" alt="Screenshot 2024-12-12 at 10 49 20 PM" src="https://github.com/user-attachments/assets/9f56fd71-c965-4d30-b25a-a12f4b2aa817" />

**Comment by boa-z** [comment]
Alternatively, when you switch between tabs on your favorite page, the same error will occur.
